### ISSUE TITLE
Timeout  error

### ISSUE THREAD

**Issue by depaolif** [learn-co-students/javascript-first-class-functions-web-0217#7]
The tests were not even showing after running the Learn command. There was only one "test", that was failing, with the description:
```
1) index "before all" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:325:18)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```
This error comes up regardless of what I have in the index.js file that's being tested. It looks like there's a problem with the tests themselves.

**Comment by depaolif** [comment]
![screen shot 2017-03-16 at 4 45 26 pm](https://cloud.githubusercontent.com/assets/21266475/24017991/87e480da-0a68-11e7-89d1-22b6e0685802.png)
for reference
